.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CONSOLE" "1" "March 2013" "" ""
.
.SH "NAME"
\fBconsole\fR \- A Read\-Eval\-Print Loop (REPL) for the PHP language\.
.
.SH "SYNOPSIS"
\fBconsole\fR [\fB\-hHqz\fR] [\fB\-c\fR \fIcolor\fR] [\fB\-f\fR \fIfile\fR] [\fB\-i\fR \fIkey=val\fR] [\fB\-p\fR \fIfile\fR] [\fB\-s\fR \fIfile\fR] [\fB\-v\fR \fIvar=val\fR]
.
.SH "DESCRIPTION"
\fBConsole\fR provides a Read\-Eval\-Print Loop (REPL) environment for the PHP language\. A REPL is an interactive programming environment\. The user enters PHP statements and expressions which are read, evaluated, and the results printed\. The REPL environment is protected from errors and exceptions, including PHP fatal and parse errors\.
.
.SH "OPTIONS"
.
.TP
\fB\-A\fR
Don\'t preload tab\-completion cache\-\-\-console starts up a little faster but tab completion is a little slower\.
.
.TP
\fB\-c\fR \fIcolor\fR
Return value print color (default is \fBcyan\fR)\. Choices are: \fBblack\fR, \fBred\fR, \fBgreen\fR, \fByellow\fR, \fBblue\fR, \fBmagenta\fR, \fBcyan\fR, \fBwhite\fR, and \fBnone\fR\. Bold colors can be specified as \fBbold\-\fR\fIcolor\fR\. Specify \fBnone\fR to disable colored output\.
.
.TP
\fB\-f\fR \fIfile\fR
Require \fIfile\fR before starting REPL\.
.
.TP
\fB\-h\fR
Print usage info and exit\.
.
.TP
\fB\-H\fR
Don\'t parse \fB\.htaccess\fR files at startup\.
.
.TP
\fB\-i\fR \fIkey=val\fR
Set PHP configuration option \fIkey\fR to \fIval\fR\.
.
.TP
\fB\-p\fR \fIfile\fR
Require \fIfile\fR before loading console\'s classloader\.
.
.TP
\fB\-q\fR
Don\'t echo the result after evaling each expression\.
.
.TP
\fB\-s\fR \fIfile\fR
Run console commands in \fIfile\fR before interactive REPL\.
.
.TP
\fB\-v\fR \fIvar=val\fR
Set \fI$var\fR to \fIval\fR globally in REPL environment\.
.
.TP
\fB\-z\fR
Run script files but don\'t start interactive REPL\.
.
.P
Multiple \fB\-f\fR, \fB\-i\fR, \fB\-p\fR, and \fB\-v\fR options may be specified on the same command line\.
.
.SH "REPL COMMANDS"
The following commands are available inside the REPL environment:
.
.TP
\fB/d\fR \fIthing\fR
Get the doc comment for the \fIthing\fR\.
.
.TP
\fB/e\fR [\fIfile\fR]
Append session history to \fIfile\fR and open in editor\. If \fIfile\fR is not specified then the file specified with the \fB\-s\fR option will be used\.
.
.TP
\fB/f\fR \fIfile\fR
Load \fIfile\fR via php\'s \fBrequire()\fR\.
.
.TP
\fB/h\fR
Print this help info\.
.
.TP
\fB/hh\fR
Print expression history\.
.
.TP
\fB/p\fR \fIexpr\fR
Toggle echoing the result just for this expression\.
.
.TP
\fB/pp\fR
Toggle echoing the result of each eval\.
.
.TP
\fB/pager\fR [\fIcmd\fR]
Pipe results through shell command \fIcmd\fR when displaying them\. If no \fIcmd\fR is provided, the current pager command is removed\.
.
.TP
\fB/q\fR \fIexpr\fR
Evaluate \fIexpr\fR but don\'t display the result\.
.
.TP
\fB/x\fR \fIexpr\fR
Evaluate \fIexpr\fR and examine result (print full \fBvar_export\fR output)\.
.
.SH "HISTORY EXPANSION"
Each statement and expression entered into the REPL is assigned a history number\. Expressions and statements previously entered can be referenced by this number at read\-time via history expansion\. The following special forms are expanded:
.
.TP
\fB$$\fR
Expands to the previous statement/expression\.
.
.TP
\fB$\fR\fIN\fR
Expands to the statement/expression corresponding to history number \fIN\fR\.
.
.TP
\fB$\fR\fI\-N\fR
Expands to the \fIN\fRth previous statement/expression\. (Note that \fB$$\fR is equivalent to \fB$\-1\fR, for example\.)
.
.TP
\fB$!\fR
Expands to the previous result\. (The previous statement or expression is not re\-evaluated\.)
.
.SH "CONFIGURATION"
Most of the REPL functionality can be modified or accessed programmatically via the \fBConsole\fR and \fBConsoleCommand\fR classes\.
.
.TP
\fBConsole::$DEBUG\fR
Extra debugging info is printed when this static property is \fBtrue\fR\.
.
.TP
\fBConsole::$PAGER\fR
Shell command to pipe results through (e\.g\. "tee /tmp/foo | more")\.
.
.TP
\fBConsole::$PS1\fR
This public static property controls how the console prompt is presented\. It may contain either a \fBprintf(\fR3\fB)\fR style format string or a callback function\. The format string or function should accept 3 arguments: history number, elapsed time, and memory used\. The callback function should return the string to be used as the prompt\.
.
.TP
\fBConsole::$PS2\fR
This public static property is a string to be used for the secondary (continued line) prompt\.
.
.TP
\fBConsole::$printers\fR
This is an array whose keys are class names and whose values are functions\. When the console displays an object of the given class, the function will be called with one argument\-\-\-the class name\. The function should return the string to be printed\. If a printer is not found for the object\'s class, then the printer for its parent class is used, if one exists, and so on\.
.
.TP
\fBConsoleCommand::add(\fRstring \fI$name\fR, callable \fI$f\fR\fB)\fR
Add a command to the REPL, accessible via \fB/\fR\fI$name\fR\. The \fI$f\fR callback should accept one argument, the rest of the command line, and it should return a string (which will be evaluated) or nothing\.
.
.TP
\fBConsoleCommand::doit(\fRstring \fI$line\fR\fB)\fR
Programmatically run the REPL command \fI$line\fR\.
.
.SH "FILES"
Console looks for the php file \fB~/\.consolerc\.php\fR\. If it finds it then that file is loaded via \fBrequire_once\fR when the REPL is started\. Additionally, the REPL can be configured via \fB\.htaccess\fR files, as usual with the Apache web server\.
.
.P
The console requires a scratch file \fB~/\.console\.php\.scratch\fR for the pager if a pager is specified, and a history file \fB~/\.console\.php\.history\fR if expression history is used\.
.
.SH "COPYRIGHT"
Wigwam is Copyright (c) 2012 Micha Niskin
.
.P
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
.
.P
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software\.
.
.P
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT\. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE\.
